import { StrictMode, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { geoNaturalEarth1, geoPath, geoInterpolate } from 'd3-geo'
import { feature } from 'topojson-client'
import worldAtlas from 'world-atlas/countries-110m.json'
import './styles.css'
import './projects.css'
import './journey.css'

const researchAreas = [
  ['01', 'Urban nature & health', 'How everyday contact with green and blue environments shapes physical activity, mental health, and wellbeing.'],
  ['02', 'Environmental behaviour', 'How people perceive, use, and move through urban landscapes — and how design can support healthier choices.'],
  ['03', 'Spatial data & AI', 'Geospatial analysis, large-scale trajectory data and explainable AI for revealing complex urban-environment relationships.'],
]
const selectedProjects = [
  { title: 'Campus green space and its effect on health and physical activities', image: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=1600&q=90', description: "As integral anchors within the contemporary megalopolis, university campuses function as sophisticated micro-urban ecosystems where the strategic deployment of green infrastructure transcends mere aesthetic utility. The campus green space acts as a vital liminal interface between the rigid urban 'grey' infrastructure and the restorative needs of the academic population. By reconfiguring the spatial logic of the urban-campus continuum, these verdant environments provide a critical therapeutic matrix that fosters physical engagement and mitigates the metabolic strains inherent in dense academic milieus. Consequently, optimizing campus landscapes is not merely an institutional prerogative; it represents a strategic contribution to urban health resilience, redefining the university as a functional node of biophilic recovery within the broader urban fabric." },
  { title: 'Health benefits of nature exposure at a national level', image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=90', description: "Evaluating the health benefits of nature exposure at a national scale necessitates a robust multi-dimensional framework that synthesizes geospatial granularity with longitudinal population health data. Such a macro-level assessment transcends localized observations, capturing the heterogeneous impacts of diverse ecological typologies—from urban green pulses to expansive wilderness—on the prevention of chronic morbidities and the enhancement of psychological resilience. By decoupling the intricate spatial dependencies between environmental affordances and socio-demographic stratification, national-level inquiry provides a pivotal evidence base for integrating 'nature-as-infrastructure' into systemic public health policies, ultimately fostering a more equitable and resilient national health landscape." },
  { title: 'Diurnal and nocturnal variations in urban green space utilization and their differential health outcomes', image: 'https://images.unsplash.com/photo-1634388400329-4b605ae63aef?auto=format&fit=crop&w=1600&q=88', description: 'The functional utility of urban green infrastructure is fundamentally defined by temporal heterogeneity, where the transition from diurnal to nocturnal cycles dictates a profound shift in the socio-environmental affordances of the urban fabric. The nocturnal green landscape introduces a distinct restorative paradigm, offering a crucial psychological refuge from the cognitive demands of modern urban life, though its efficacy is significantly moderated by artificial lightscapes and perceived safety. Understanding this day-night dichotomy is essential for advancing biophilic urbanism, as it ensures that green spaces serve as continuous, 24-hour therapeutic matrices that align with the physiological and social rhythms of a diverse citizenry. Neglecting the nocturnal dimension risks a partial understanding of how environmental exposure promotes urban health resilience across the full circadian spectrum.' },
  { title: 'Health Impact Assessments (HIA) to quantify preventable mortality attributable to green space exposure', image: 'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1600&q=90', description: "The implementation of Health Impact Assessments represents a critical methodology for translating the environmental affordances of green infrastructure into quantifiable public health outcomes. By integrating high-resolution geospatial data with robust Exposure-Response Functions, HIAs facilitate the estimation of preventable mortality—or avoidable deaths—that would occur under varying counterfactual scenarios of green space exposure. This analytical framework provides policymakers with a standardized metric to evaluate the 'life-saving potential' of ecological interventions. The systematic calculation of avoidable deaths serves as a pivotal evidence base for shifting urban planning from a purely aesthetic focus to a health-centric governance model, ensuring that nature-based solutions are prioritized as essential public health infrastructure." },
]
const publications = [
  { year: '2026', title: 'How objective natural environment, subjective nature connectedness and naturalness preference jointly shape mental health throughout China', journal: 'Environmental Impact Assessment Review', url: 'https://www.sciencedirect.com/science/article/abs/pii/S0195925526002192' },
  { year: '2026', title: 'Toward nature, our haven: Decoding the heterogeneity of non-linear associations between nature exposure and mental health during the pandemic', journal: 'Landscape Architecture and Sustainability', url: 'https://www.sciencedirect.com/science/article/pii/S3050732426000272' },
  { year: '2026', title: 'The effect of training in green space on young athletes’ sports competition anxiety: a quasi-experimental study', journal: 'International Journal of Sport and Exercise Psychology', url: 'https://www.tandfonline.com/doi/abs/10.1080/1612197X.2025.2611832' },
  { year: '2025', title: 'Walking, jogging or cycling? Exploring the associations between campus greenway environment and physical activity using large-scale trajectory data', journal: 'People and Nature', url: 'https://besjournals.onlinelibrary.wiley.com/doi/10.1002/pan3.70142' },
  { year: '2025', title: 'Greener is not always better: Exploring the non-linear relationships between three-dimensional green and gray spaces exposure and various physical activities', journal: 'Building and Environment', url: 'https://scholar.google.com/citations?user=z0SQ7CUAAAAJ&hl=en&oi=ao' },
  { year: '2024', title: 'The greener the living environment, the better the health? Examining the effects of multiple green exposure metrics on physical activity and health among young students', journal: 'Environmental Research', url: 'https://scholar.google.com/citations?user=z0SQ7CUAAAAJ&hl=en&oi=ao' },
]
function Arrow() { return <span className="arrow" aria-hidden="true">↗</span> }
const education = [
  { city: 'Auckland', years: '2026/03 — NOW', degree: 'PhD Student', school: 'Faculty of Engineering and Design, Architecture and Planning', university: 'University of Auckland', note: 'The University of Auckland Doctoral Scholarship (UoADS)', coordinates: [174.7681, -36.8522] },
  { city: 'Shanghai', years: '2023/09 — 2025/06', degree: 'Academic Master of Landscape Architecture (Science)', school: 'School of Design', university: 'Shanghai Jiao Tong University', coordinates: [121.4737, 31.2304] },
  { city: 'Nanjing', years: '2019/09 — 2023/06', degree: 'Bachelor of Landscape Architecture', school: 'College of Landscape Architecture', university: 'Nanjing Forestry University', coordinates: [118.7969, 32.0603] },
]
const countries = feature(worldAtlas, worldAtlas.objects.countries)
const journeyCountries = { type: 'FeatureCollection', features: countries.features.filter((country) => ['156', '554'].includes(String(country.id))) }
const projection = geoNaturalEarth1().fitExtent([[78, 54], [822, 504]], journeyCountries)
const routePath = (start, end) => geoPath(projection)({ type: 'LineString', coordinates: Array.from({ length: 51 }, (_, index) => geoInterpolate(start, end)(index / 50)) })
function EducationJourney() {
  const [activeCity, setActiveCity] = useState('Auckland')
  const active = education.find((item) => item.city === activeCity)
  return <section className="journey" aria-labelledby="journey-title"><div className="journey-heading"><div><p className="section-index">( EDUCATION )</p><h2 id="journey-title">A path across<br /><em>landscapes.</em></h2></div><p>From Nanjing and Shanghai to Auckland — an academic journey across landscape architecture, design, and urban health.</p></div><div className="journey-layout"><div className="education-list">{education.map((item) => <button type="button" className={`education-item ${activeCity === item.city ? 'is-active' : ''}`} onClick={() => setActiveCity(item.city)} key={item.city}><span>{item.years}</span><strong>{item.degree}</strong><p>{item.school}<br /><em>{item.university}</em></p>{item.note && <small>{item.note}</small>}</button>)}</div><div className="journey-map" aria-label="Academic journey map"><svg viewBox="0 0 900 560" role="img" aria-labelledby="map-title map-description"><title id="map-title">Academic journey route</title><desc id="map-description">An abstract route showing the academic journey from Nanjing to Shanghai and Auckland.</desc><g className="map-grid"><path d="M0 112h900M0 224h900M0 336h900M0 448h900M150 0v560M300 0v560M450 0v560M600 0v560M750 0v560" /></g><path className="route route-short" d={routePath(education[2].coordinates, education[1].coordinates)} /><path className="route route-long" d={routePath(education[1].coordinates, education[0].coordinates)} /><path className="route route-pulse" d={routePath(education[1].coordinates, education[0].coordinates)} /></svg>{education.map((item) => { const [x, y] = projection(item.coordinates); return <button type="button" aria-label={item.city} aria-pressed={activeCity === item.city} className={`map-point point-${item.city.toLowerCase()} ${activeCity === item.city ? 'is-active' : ''}`} style={{ left: `${(x / 900) * 100}%`, top: `${(y / 560) * 100}%` }} onClick={() => setActiveCity(item.city)} key={item.city}><span className="point-dot" /></button> })}<div className="map-detail" aria-live="polite"><span>{active.years}</span><strong>{active.city}</strong><p>{active.degree}</p></div></div></div></section>
}
function App() { return <main>
  <section className="hero" id="top"><img className="hero-image" src="https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=2400&q=90" alt="Tree canopy viewed from below" /><div className="hero-overlay" />
    <nav className="nav shell"><a className="wordmark" href="#top">YUHENG MAO<span> / RESEARCH</span></a><div className="nav-links"><a href="#about">ABOUT</a><a href="#research">RESEARCH</a><a href="#publications">PUBLICATIONS</a></div><a className="contact-pill" href="#contact">CONTACT <Arrow /></a></nav>
    <div className="hero-content shell"><p className="eyebrow">URBAN LANDSCAPES · HUMAN HEALTH · SPATIAL INTELLIGENCE</p><h1>Yuheng<br /><em>Mao.</em></h1><div className="hero-bottom"><p>PhD Candidate<br />University of Auckland</p><a href="#research" className="scroll-link">EXPLORE THE RESEARCH <span>↓</span></a></div></div>
  </section>
  <section className="about shell section" id="about"><p className="section-index">( 01 — ABOUT )</p><div className="about-grid"><div className="portrait-wrap"><img src="https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1000&q=90" alt="Aerial view of an urban landscape" /><span className="portrait-caption">AUCKLAND, AOTEAROA<br />NEW ZEALAND</span></div><div className="about-copy"><p className="lead">I study the relationships between urban landscapes and people — with a focus on environment, health, policy, and behaviour.</p><p className="body-copy">My work brings landscape architecture, public health, and spatial analysis into conversation. I am interested in how the everyday environments around us can be measured, understood, and designed to support more equitable and healthy urban life.</p><div className="details"><a href="https://profiles.auckland.ac.nz/yuheng-mao/about" target="_blank" rel="noreferrer">UNIVERSITY OF AUCKLAND PROFILE <Arrow /></a><span>FACULTY OF ENGINEERING AND DESIGN</span></div></div></div><div className="focus-line"><span>RESEARCH FOCUS</span><p>Urban green space · Environmental exposure · Physical activity · Population health · Geospatial AI</p></div><EducationJourney /></section>
  <section className="research section" id="research"><div className="shell research-heading"><p className="section-index">( 02 — RESEARCH )</p><h2>Evidence for<br /><em>better cities.</em></h2><p>Connecting environmental conditions with the experiences and health of urban populations.</p></div><div className="research-list shell">{researchAreas.map(([num, title, copy]) => <article className="research-card" key={num}><div><span>{num}</span><h3>{title}</h3></div><p>{copy}</p><Arrow /></article>)}</div><div className="projects shell"><div className="projects-label"><p className="section-index">( SELECTED PROJECTS )</p><p>Current research projects on the environmental foundations of healthier urban life.</p></div><div className="project-grid">{selectedProjects.map((project, index) => <article className="project-card" key={project.title}><div className="project-image"><img src={project.image} alt="" /><span>0{index + 1}</span></div><div className="project-copy"><h3>{project.title}</h3><p>{project.description}</p></div></article>)}</div></div></section>
  <section className="publications shell section" id="publications"><div className="publications-heading"><p className="section-index">( 03 — SELECTED PUBLICATIONS )</p><h2>Research<br /><em>outputs.</em></h2><a href="https://scholar.google.com/citations?user=z0SQ7CUAAAAJ&hl=en&oi=ao" target="_blank" rel="noreferrer" className="outline-link">VIEW GOOGLE SCHOLAR <Arrow /></a></div><div className="publication-list">{publications.map((paper, i) => <a href={paper.url} target="_blank" rel="noreferrer" className="publication" key={paper.title}><span className="pub-index">0{i + 1}</span><span className="pub-year">{paper.year}</span><div><h3>{paper.title}</h3><p>{paper.journal}</p></div><Arrow /></a>)}</div></section>
  <section className="contact" id="contact"><div className="contact-orb orb-a" /><div className="contact-orb orb-b" /><div className="shell contact-inner"><p className="section-index">( 04 — CONNECT )</p><p className="contact-kicker">For research collaborations, speaking, and academic conversations.</p><a className="contact-title" href="https://profiles.auckland.ac.nz/yuheng-mao/about" target="_blank" rel="noreferrer">Start a<br /><em>conversation.</em> <Arrow /></a><div className="contact-footer"><a href="https://profiles.auckland.ac.nz/yuheng-mao/about" target="_blank" rel="noreferrer">UNIVERSITY PROFILE</a><span>© 2026 YUHENG MAO</span><a href="#top">BACK TO TOP ↑</a></div></div></section>
</main> }
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)

